language: go

os:
  - linux
  - osx

install:
  # install Glide
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install

script:
  - make test-coverage
  - make
