language: go
branches:
  only:
  - master
os:
  - linux

go:
  - "1.12"

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - gem install sass --version "=3.5.6"

cache:
  directories:
  - "$HOME/.yarn-cache"

before_script:
  - nvm install 6
  - npm install -g typescript

script:
  - make test-coverage
  - make
  - cd client && yarn install && yarn run lint
  - sass src/css/stylesheet.scss src/css/stylesheet.css
  - tsc
  - cd ..
  - zip -r x86_linux.zip bin/ client/src/ can_messages.asciipb driver_display_startup.sh
  - env GOOS=linux GOARCH=arm GOARM=5 make
  - zip -r arm32_linux.zip bin/ client/src/ can_messages.asciipb driver_display_startup.sh

deploy:
  provider: releases
  api_key:
    secure: F7su/Zj9ZciApSZima5zoh0JIiaN5PjcOEA1Z4Id6Lqhw6p05aAQvHK+wt13RO6vDJXt3b+tEXiF5127+vrnpgQaWPjLXDR//gx0kGoRLWXru2+VXxqUdXFalubZuoV6ehpd3wO4kbM261GS6fc0DbZgAXpGXeJjQtc26yct5afOZpWQ61fvJjXaA+sP9D1aA/OMHO3Rl4V/dskL1HW/mHiUjdlsagxUOjCaeHJnXm/6RYPxIcoaiQcc61wh7kwk2CH5mTzUufv5AZm3DYmNVwYmsKWL2z8WKXlZ9ITlr3J3Q7Vjml1FWBjE4Zsy4PTHKb5wLe0LOpIm2S6itpWQ8Q2jPsRYpR/ZOoGQThNT6Cva55h6Ns0MgjiALsVQSzAvKeM2n5Le5kuMKMFJwQVswiGYAN/1JnfhyJAldr7PX3fLV3nNxoP0ccQfwmQo6AlTI+RW+Uxz3L0OxvCBf5qIdAet+Ykkph+teChMPfDrYPbi75IzkBZIU1YhxEQqi1HZojREYeqeJma+hpebN433w1WvJnAfUPL54fVsX6sz18B0Um5F/oYTdAc3U3vN8BfOS4Gghdnxppg3cZn9m2hGrB60Q0bywqiUwn3PuWo/10jeJxJ/v2tp8uKKpVY38Zt3rHUrInzeqaMXCElnL54uEi0/wJrxKI1kOSTG4MASbMc=
  file: 
    - x86_linux.zip
    - arm32_linux.zip
  skip_cleanup: true
  on:
    repo: uw-midsun/telemetry
