package canmsgdefs

// NOTE: This file is generated by codegen-tooling.
// Currently, this file is copy-pasted from codegen output
// to canmsgdefs in the telemetry server.

// TODO: Automate this process.

// CanDeviceID is a 16-bit integer for the source of a CAN message
type CanDeviceID uint16

// CanMsgID is a 32-bit integer for the type of CAN message
type CanMsgID uint32

// For setting the CAN device
const (
	SystemCanDeviceReserved                    CanDeviceID = 0
	SystemCanDevicePlutus                      CanDeviceID = 1
	SystemCanDevicePlutusSlave                 CanDeviceID = 2
	SystemCanDeviceChaos                       CanDeviceID = 3
	SystemCanDeviceTelemetry                   CanDeviceID = 4
	SystemCanDeviceLightsFront                 CanDeviceID = 5
	SystemCanDeviceLightsRear                  CanDeviceID = 6
	SystemCanDeviceMotorController             CanDeviceID = 7
	SystemCanDeviceDriverControlsPedal         CanDeviceID = 8
	SystemCanDeviceDriverControlsCenterConsole CanDeviceID = 9
	SystemCanDeviceSolarMasterFront            CanDeviceID = 10
	SystemCanDeviceSolarMasterRear             CanDeviceID = 11
	SystemCanDeviceSensorBoard                 CanDeviceID = 12
	SystemCanDeviceCharger                     CanDeviceID = 13
	SystemCanDeviceDriverControlsSteering      CanDeviceID = 14
)

// For setting the CAN message ID
const (
	SystemCanMessageBpsHeartbeat                       CanMsgID = 0
	SystemCanMessagePowerDistributionFault             CanMsgID = 1
	SystemCanMessageBatteryRelayMain                   CanMsgID = 2
	SystemCanMessageBatteryRelaySlave                  CanMsgID = 3
	SystemCanMessageMotorRelay                         CanMsgID = 4
	SystemCanMessageSolarRelayRear                     CanMsgID = 5
	SystemCanMessageSolarRelayFront                    CanMsgID = 6
	SystemCanMessagePowerState                         CanMsgID = 7
	SystemCanMessagePowertrainHeartbeat                CanMsgID = 8
	SystemCanMessageOvuvDcdcAux                        CanMsgID = 16
	SystemCanMessageMcErrorLimits                      CanMsgID = 17
	SystemCanMessageDriveOutput                        CanMsgID = 18
	SystemCanMessageCruiseTarget                       CanMsgID = 19
	SystemCanMessageFanControl                         CanMsgID = 20
	SystemCanMessageSetModuleDischarge                 CanMsgID = 21
	SystemCanMessageDischargeState                     CanMsgID = 22
	SystemCanMessageLightsSync                         CanMsgID = 23
	SystemCanMessageLightsState                        CanMsgID = 24
	SystemCanMessageHorn                               CanMsgID = 25
	SystemCanMessageChargerConnState                   CanMsgID = 26
	SystemCanMessageChargerSetRelayState               CanMsgID = 27
	SystemCanMessageSteeringEvent                      CanMsgID = 28
	SystemCanMessageCenterConsoleEvent                 CanMsgID = 29
	SystemCanMessageMotorControllerReset               CanMsgID = 30
	SystemCanMessageBatterySoc                         CanMsgID = 31
	SystemCanMessageBatteryVt                          CanMsgID = 32
	SystemCanMessageBatteryAggregateVc                 CanMsgID = 33
	SystemCanMessageMotorControllerVc                  CanMsgID = 35
	SystemCanMessageMotorVelocity                      CanMsgID = 36
	SystemCanMessageMotorDebug                         CanMsgID = 37
	SystemCanMessageMotorTemps                         CanMsgID = 38
	SystemCanMessageMotorAmpHr                         CanMsgID = 39
	SystemCanMessageOdometer                           CanMsgID = 40
	SystemCanMessageAuxDcdcVc                          CanMsgID = 43
	SystemCanMessageDcdcTemps                          CanMsgID = 44
	SystemCanMessageSolarDataFront                     CanMsgID = 45
	SystemCanMessageSolarDataRear                      CanMsgID = 46
	SystemCanMessageChargerInfo                        CanMsgID = 47
	SystemCanMessageLinearAcceleration                 CanMsgID = 51
	SystemCanMessageAngularRotation                    CanMsgID = 52
	SystemCanMessageGpsUtcTime                         CanMsgID = 53
	SystemCanMessageGpsLongitudeAndSatelitesUsed       CanMsgID = 54
	SystemCanMessageGpsLatitudeAndPositionFixIndicator CanMsgID = 55
	SystemCanMessageGpsSpeedAndTrueHeading             CanMsgID = 56
)
