// Code generated by protoc-gen-go. DO NOT EDIT.
// source: can.proto

package can

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CanMsg_Source int32

const (
	CanMsg_RESERVED           CanMsg_Source = 0
	CanMsg_PLUTUS             CanMsg_Source = 1
	CanMsg_PLUTUS_SLAVE       CanMsg_Source = 2
	CanMsg_CHAOS              CanMsg_Source = 3
	CanMsg_TELEMETRY          CanMsg_Source = 4
	CanMsg_LIGHTS_FRONT       CanMsg_Source = 5
	CanMsg_LIGHTS_REAR        CanMsg_Source = 6
	CanMsg_MOTOR_CONTROLLER   CanMsg_Source = 7
	CanMsg_DRIVER_CONTROLS    CanMsg_Source = 8
	CanMsg_DRIVER_DISPLAY     CanMsg_Source = 9
	CanMsg_SOLAR_MASTER_FRONT CanMsg_Source = 10
	CanMsg_SOLAR_MASTER_REAR  CanMsg_Source = 11
	CanMsg_SENSOR_BOARD       CanMsg_Source = 12
	CanMsg_CHARGER            CanMsg_Source = 13
)

var CanMsg_Source_name = map[int32]string{
	0:  "RESERVED",
	1:  "PLUTUS",
	2:  "PLUTUS_SLAVE",
	3:  "CHAOS",
	4:  "TELEMETRY",
	5:  "LIGHTS_FRONT",
	6:  "LIGHTS_REAR",
	7:  "MOTOR_CONTROLLER",
	8:  "DRIVER_CONTROLS",
	9:  "DRIVER_DISPLAY",
	10: "SOLAR_MASTER_FRONT",
	11: "SOLAR_MASTER_REAR",
	12: "SENSOR_BOARD",
	13: "CHARGER",
}
var CanMsg_Source_value = map[string]int32{
	"RESERVED":           0,
	"PLUTUS":             1,
	"PLUTUS_SLAVE":       2,
	"CHAOS":              3,
	"TELEMETRY":          4,
	"LIGHTS_FRONT":       5,
	"LIGHTS_REAR":        6,
	"MOTOR_CONTROLLER":   7,
	"DRIVER_CONTROLS":    8,
	"DRIVER_DISPLAY":     9,
	"SOLAR_MASTER_FRONT": 10,
	"SOLAR_MASTER_REAR":  11,
	"SENSOR_BOARD":       12,
	"CHARGER":            13,
}

func (x CanMsg_Source) String() string {
	return proto.EnumName(CanMsg_Source_name, int32(x))
}
func (CanMsg_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{6, 0}
}

// NEXT TAG = 9
type FrameU8 struct {
	FieldName_1          string   `protobuf:"bytes,1,opt,name=field_name_1,json=fieldName1,proto3" json:"field_name_1,omitempty"`
	FieldName_2          string   `protobuf:"bytes,2,opt,name=field_name_2,json=fieldName2,proto3" json:"field_name_2,omitempty"`
	FieldName_3          string   `protobuf:"bytes,3,opt,name=field_name_3,json=fieldName3,proto3" json:"field_name_3,omitempty"`
	FieldName_4          string   `protobuf:"bytes,4,opt,name=field_name_4,json=fieldName4,proto3" json:"field_name_4,omitempty"`
	FieldName_5          string   `protobuf:"bytes,5,opt,name=field_name_5,json=fieldName5,proto3" json:"field_name_5,omitempty"`
	FieldName_6          string   `protobuf:"bytes,6,opt,name=field_name_6,json=fieldName6,proto3" json:"field_name_6,omitempty"`
	FieldName_7          string   `protobuf:"bytes,7,opt,name=field_name_7,json=fieldName7,proto3" json:"field_name_7,omitempty"`
	FieldName_8          string   `protobuf:"bytes,8,opt,name=field_name_8,json=fieldName8,proto3" json:"field_name_8,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameU8) Reset()         { *m = FrameU8{} }
func (m *FrameU8) String() string { return proto.CompactTextString(m) }
func (*FrameU8) ProtoMessage()    {}
func (*FrameU8) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{0}
}
func (m *FrameU8) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameU8.Unmarshal(m, b)
}
func (m *FrameU8) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameU8.Marshal(b, m, deterministic)
}
func (dst *FrameU8) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameU8.Merge(dst, src)
}
func (m *FrameU8) XXX_Size() int {
	return xxx_messageInfo_FrameU8.Size(m)
}
func (m *FrameU8) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameU8.DiscardUnknown(m)
}

var xxx_messageInfo_FrameU8 proto.InternalMessageInfo

func (m *FrameU8) GetFieldName_1() string {
	if m != nil {
		return m.FieldName_1
	}
	return ""
}

func (m *FrameU8) GetFieldName_2() string {
	if m != nil {
		return m.FieldName_2
	}
	return ""
}

func (m *FrameU8) GetFieldName_3() string {
	if m != nil {
		return m.FieldName_3
	}
	return ""
}

func (m *FrameU8) GetFieldName_4() string {
	if m != nil {
		return m.FieldName_4
	}
	return ""
}

func (m *FrameU8) GetFieldName_5() string {
	if m != nil {
		return m.FieldName_5
	}
	return ""
}

func (m *FrameU8) GetFieldName_6() string {
	if m != nil {
		return m.FieldName_6
	}
	return ""
}

func (m *FrameU8) GetFieldName_7() string {
	if m != nil {
		return m.FieldName_7
	}
	return ""
}

func (m *FrameU8) GetFieldName_8() string {
	if m != nil {
		return m.FieldName_8
	}
	return ""
}

// NEXT TAG = 5
type FrameU16 struct {
	FieldName_1          string   `protobuf:"bytes,1,opt,name=field_name_1,json=fieldName1,proto3" json:"field_name_1,omitempty"`
	FieldName_2          string   `protobuf:"bytes,2,opt,name=field_name_2,json=fieldName2,proto3" json:"field_name_2,omitempty"`
	FieldName_3          string   `protobuf:"bytes,3,opt,name=field_name_3,json=fieldName3,proto3" json:"field_name_3,omitempty"`
	FieldName_4          string   `protobuf:"bytes,4,opt,name=field_name_4,json=fieldName4,proto3" json:"field_name_4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameU16) Reset()         { *m = FrameU16{} }
func (m *FrameU16) String() string { return proto.CompactTextString(m) }
func (*FrameU16) ProtoMessage()    {}
func (*FrameU16) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{1}
}
func (m *FrameU16) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameU16.Unmarshal(m, b)
}
func (m *FrameU16) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameU16.Marshal(b, m, deterministic)
}
func (dst *FrameU16) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameU16.Merge(dst, src)
}
func (m *FrameU16) XXX_Size() int {
	return xxx_messageInfo_FrameU16.Size(m)
}
func (m *FrameU16) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameU16.DiscardUnknown(m)
}

var xxx_messageInfo_FrameU16 proto.InternalMessageInfo

func (m *FrameU16) GetFieldName_1() string {
	if m != nil {
		return m.FieldName_1
	}
	return ""
}

func (m *FrameU16) GetFieldName_2() string {
	if m != nil {
		return m.FieldName_2
	}
	return ""
}

func (m *FrameU16) GetFieldName_3() string {
	if m != nil {
		return m.FieldName_3
	}
	return ""
}

func (m *FrameU16) GetFieldName_4() string {
	if m != nil {
		return m.FieldName_4
	}
	return ""
}

// NEXT TAG = 3
type FrameU32 struct {
	FieldName_1          string   `protobuf:"bytes,1,opt,name=field_name_1,json=fieldName1,proto3" json:"field_name_1,omitempty"`
	FieldName_2          string   `protobuf:"bytes,2,opt,name=field_name_2,json=fieldName2,proto3" json:"field_name_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameU32) Reset()         { *m = FrameU32{} }
func (m *FrameU32) String() string { return proto.CompactTextString(m) }
func (*FrameU32) ProtoMessage()    {}
func (*FrameU32) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{2}
}
func (m *FrameU32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameU32.Unmarshal(m, b)
}
func (m *FrameU32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameU32.Marshal(b, m, deterministic)
}
func (dst *FrameU32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameU32.Merge(dst, src)
}
func (m *FrameU32) XXX_Size() int {
	return xxx_messageInfo_FrameU32.Size(m)
}
func (m *FrameU32) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameU32.DiscardUnknown(m)
}

var xxx_messageInfo_FrameU32 proto.InternalMessageInfo

func (m *FrameU32) GetFieldName_1() string {
	if m != nil {
		return m.FieldName_1
	}
	return ""
}

func (m *FrameU32) GetFieldName_2() string {
	if m != nil {
		return m.FieldName_2
	}
	return ""
}

// NEXT TAG = 2
type FrameU64 struct {
	FieldName_1          string   `protobuf:"bytes,1,opt,name=field_name_1,json=fieldName1,proto3" json:"field_name_1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameU64) Reset()         { *m = FrameU64{} }
func (m *FrameU64) String() string { return proto.CompactTextString(m) }
func (*FrameU64) ProtoMessage()    {}
func (*FrameU64) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{3}
}
func (m *FrameU64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameU64.Unmarshal(m, b)
}
func (m *FrameU64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameU64.Marshal(b, m, deterministic)
}
func (dst *FrameU64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameU64.Merge(dst, src)
}
func (m *FrameU64) XXX_Size() int {
	return xxx_messageInfo_FrameU64.Size(m)
}
func (m *FrameU64) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameU64.DiscardUnknown(m)
}

var xxx_messageInfo_FrameU64 proto.InternalMessageInfo

func (m *FrameU64) GetFieldName_1() string {
	if m != nil {
		return m.FieldName_1
	}
	return ""
}

// NEXT TAG = 1
type FrameEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameEmpty) Reset()         { *m = FrameEmpty{} }
func (m *FrameEmpty) String() string { return proto.CompactTextString(m) }
func (*FrameEmpty) ProtoMessage()    {}
func (*FrameEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{4}
}
func (m *FrameEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameEmpty.Unmarshal(m, b)
}
func (m *FrameEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameEmpty.Marshal(b, m, deterministic)
}
func (dst *FrameEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameEmpty.Merge(dst, src)
}
func (m *FrameEmpty) XXX_Size() int {
	return xxx_messageInfo_FrameEmpty.Size(m)
}
func (m *FrameEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_FrameEmpty proto.InternalMessageInfo

// NEXT TAG = 7
type CanData struct {
	Data uint64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	// Types that are valid to be assigned to Frame:
	//	*CanData_U8
	//	*CanData_U16
	//	*CanData_U32
	//	*CanData_U64
	//	*CanData_Empty
	Frame                isCanData_Frame `protobuf_oneof:"frame"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CanData) Reset()         { *m = CanData{} }
func (m *CanData) String() string { return proto.CompactTextString(m) }
func (*CanData) ProtoMessage()    {}
func (*CanData) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{5}
}
func (m *CanData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanData.Unmarshal(m, b)
}
func (m *CanData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanData.Marshal(b, m, deterministic)
}
func (dst *CanData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanData.Merge(dst, src)
}
func (m *CanData) XXX_Size() int {
	return xxx_messageInfo_CanData.Size(m)
}
func (m *CanData) XXX_DiscardUnknown() {
	xxx_messageInfo_CanData.DiscardUnknown(m)
}

var xxx_messageInfo_CanData proto.InternalMessageInfo

type isCanData_Frame interface {
	isCanData_Frame()
}

type CanData_U8 struct {
	U8 *FrameU8 `protobuf:"bytes,2,opt,name=u8,proto3,oneof"`
}
type CanData_U16 struct {
	U16 *FrameU16 `protobuf:"bytes,3,opt,name=u16,proto3,oneof"`
}
type CanData_U32 struct {
	U32 *FrameU32 `protobuf:"bytes,4,opt,name=u32,proto3,oneof"`
}
type CanData_U64 struct {
	U64 *FrameU64 `protobuf:"bytes,5,opt,name=u64,proto3,oneof"`
}
type CanData_Empty struct {
	Empty *FrameEmpty `protobuf:"bytes,6,opt,name=empty,proto3,oneof"`
}

func (*CanData_U8) isCanData_Frame()    {}
func (*CanData_U16) isCanData_Frame()   {}
func (*CanData_U32) isCanData_Frame()   {}
func (*CanData_U64) isCanData_Frame()   {}
func (*CanData_Empty) isCanData_Frame() {}

func (m *CanData) GetFrame() isCanData_Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *CanData) GetData() uint64 {
	if m != nil {
		return m.Data
	}
	return 0
}

func (m *CanData) GetU8() *FrameU8 {
	if x, ok := m.GetFrame().(*CanData_U8); ok {
		return x.U8
	}
	return nil
}

func (m *CanData) GetU16() *FrameU16 {
	if x, ok := m.GetFrame().(*CanData_U16); ok {
		return x.U16
	}
	return nil
}

func (m *CanData) GetU32() *FrameU32 {
	if x, ok := m.GetFrame().(*CanData_U32); ok {
		return x.U32
	}
	return nil
}

func (m *CanData) GetU64() *FrameU64 {
	if x, ok := m.GetFrame().(*CanData_U64); ok {
		return x.U64
	}
	return nil
}

func (m *CanData) GetEmpty() *FrameEmpty {
	if x, ok := m.GetFrame().(*CanData_Empty); ok {
		return x.Empty
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CanData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CanData_OneofMarshaler, _CanData_OneofUnmarshaler, _CanData_OneofSizer, []interface{}{
		(*CanData_U8)(nil),
		(*CanData_U16)(nil),
		(*CanData_U32)(nil),
		(*CanData_U64)(nil),
		(*CanData_Empty)(nil),
	}
}

func _CanData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CanData)
	// frame
	switch x := m.Frame.(type) {
	case *CanData_U8:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.U8); err != nil {
			return err
		}
	case *CanData_U16:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.U16); err != nil {
			return err
		}
	case *CanData_U32:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.U32); err != nil {
			return err
		}
	case *CanData_U64:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.U64); err != nil {
			return err
		}
	case *CanData_Empty:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Empty); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CanData.Frame has unexpected type %T", x)
	}
	return nil
}

func _CanData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CanData)
	switch tag {
	case 2: // frame.u8
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameU8)
		err := b.DecodeMessage(msg)
		m.Frame = &CanData_U8{msg}
		return true, err
	case 3: // frame.u16
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameU16)
		err := b.DecodeMessage(msg)
		m.Frame = &CanData_U16{msg}
		return true, err
	case 4: // frame.u32
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameU32)
		err := b.DecodeMessage(msg)
		m.Frame = &CanData_U32{msg}
		return true, err
	case 5: // frame.u64
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameU64)
		err := b.DecodeMessage(msg)
		m.Frame = &CanData_U64{msg}
		return true, err
	case 6: // frame.empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameEmpty)
		err := b.DecodeMessage(msg)
		m.Frame = &CanData_Empty{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CanData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CanData)
	// frame
	switch x := m.Frame.(type) {
	case *CanData_U8:
		s := proto.Size(x.U8)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CanData_U16:
		s := proto.Size(x.U16)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CanData_U32:
		s := proto.Size(x.U32)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CanData_U64:
		s := proto.Size(x.U64)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CanData_Empty:
		s := proto.Size(x.Empty)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// NEXT TAG = 9
type CanMsg struct {
	RawId                uint32        `protobuf:"varint,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	Source               CanMsg_Source `protobuf:"varint,2,opt,name=source,proto3,enum=CanMsg_Source" json:"source,omitempty"`
	IsAck                bool          `protobuf:"varint,3,opt,name=is_ack,json=isAck,proto3" json:"is_ack,omitempty"`
	Id                   uint32        `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	CanData              *CanData      `protobuf:"bytes,5,opt,name=can_data,json=canData,proto3" json:"can_data,omitempty"`
	MsgName              string        `protobuf:"bytes,6,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	MsgReadableName      string        `protobuf:"bytes,7,opt,name=msg_readable_name,json=msgReadableName,proto3" json:"msg_readable_name,omitempty"`
	IsCritical           bool          `protobuf:"varint,8,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CanMsg) Reset()         { *m = CanMsg{} }
func (m *CanMsg) String() string { return proto.CompactTextString(m) }
func (*CanMsg) ProtoMessage()    {}
func (*CanMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{6}
}
func (m *CanMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanMsg.Unmarshal(m, b)
}
func (m *CanMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanMsg.Marshal(b, m, deterministic)
}
func (dst *CanMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanMsg.Merge(dst, src)
}
func (m *CanMsg) XXX_Size() int {
	return xxx_messageInfo_CanMsg.Size(m)
}
func (m *CanMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CanMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CanMsg proto.InternalMessageInfo

func (m *CanMsg) GetRawId() uint32 {
	if m != nil {
		return m.RawId
	}
	return 0
}

func (m *CanMsg) GetSource() CanMsg_Source {
	if m != nil {
		return m.Source
	}
	return CanMsg_RESERVED
}

func (m *CanMsg) GetIsAck() bool {
	if m != nil {
		return m.IsAck
	}
	return false
}

func (m *CanMsg) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CanMsg) GetCanData() *CanData {
	if m != nil {
		return m.CanData
	}
	return nil
}

func (m *CanMsg) GetMsgName() string {
	if m != nil {
		return m.MsgName
	}
	return ""
}

func (m *CanMsg) GetMsgReadableName() string {
	if m != nil {
		return m.MsgReadableName
	}
	return ""
}

func (m *CanMsg) GetIsCritical() bool {
	if m != nil {
		return m.IsCritical
	}
	return false
}

// NEXT TAG = 2
type CanSchema struct {
	Msg                  []*CanMsg `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CanSchema) Reset()         { *m = CanSchema{} }
func (m *CanSchema) String() string { return proto.CompactTextString(m) }
func (*CanSchema) ProtoMessage()    {}
func (*CanSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_can_098a620eea6f59af, []int{7}
}
func (m *CanSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanSchema.Unmarshal(m, b)
}
func (m *CanSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanSchema.Marshal(b, m, deterministic)
}
func (dst *CanSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanSchema.Merge(dst, src)
}
func (m *CanSchema) XXX_Size() int {
	return xxx_messageInfo_CanSchema.Size(m)
}
func (m *CanSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CanSchema.DiscardUnknown(m)
}

var xxx_messageInfo_CanSchema proto.InternalMessageInfo

func (m *CanSchema) GetMsg() []*CanMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*FrameU8)(nil), "FrameU8")
	proto.RegisterType((*FrameU16)(nil), "FrameU16")
	proto.RegisterType((*FrameU32)(nil), "FrameU32")
	proto.RegisterType((*FrameU64)(nil), "FrameU64")
	proto.RegisterType((*FrameEmpty)(nil), "FrameEmpty")
	proto.RegisterType((*CanData)(nil), "CanData")
	proto.RegisterType((*CanMsg)(nil), "CanMsg")
	proto.RegisterType((*CanSchema)(nil), "CanSchema")
	proto.RegisterEnum("CanMsg_Source", CanMsg_Source_name, CanMsg_Source_value)
}

func init() { proto.RegisterFile("can.proto", fileDescriptor_can_098a620eea6f59af) }

var fileDescriptor_can_098a620eea6f59af = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xfd, 0x4f, 0x7f, 0x3c, 0xb2, 0x1d, 0x65, 0xdb, 0x14, 0xb5, 0x50, 0x1a, 0x14, 0x08,
	0xa1, 0x14, 0x83, 0x65, 0x47, 0xf1, 0x55, 0xb1, 0x37, 0xb1, 0x41, 0xb6, 0xc2, 0x48, 0x09, 0xe4,
	0x24, 0x36, 0xb2, 0xe2, 0x8a, 0x44, 0x4e, 0xb0, 0x6c, 0x42, 0x5f, 0xa3, 0xb7, 0xbe, 0x4f, 0x1f,
	0xab, 0x94, 0xa2, 0x95, 0xd2, 0xd0, 0xbd, 0xf4, 0xd2, 0x43, 0x6f, 0xe2, 0xfb, 0x7e, 0xbb, 0x3b,
	0xf3, 0xcd, 0x20, 0x68, 0x46, 0x6c, 0xd5, 0x7d, 0x5c, 0x3f, 0x6c, 0x1e, 0xcc, 0x6f, 0x35, 0x50,
	0xce, 0xd6, 0x2c, 0x8d, 0x2f, 0x87, 0x64, 0x1f, 0x5a, 0xb7, 0x49, 0x7c, 0xbf, 0x08, 0x57, 0x2c,
	0x8d, 0xc3, 0x9e, 0x51, 0xdd, 0xaf, 0x1e, 0x35, 0x11, 0xb8, 0x36, 0x67, 0x69, 0xdc, 0x13, 0x08,
	0xcb, 0xa8, 0x09, 0x84, 0x25, 0x10, 0x7d, 0xa3, 0x2e, 0x10, 0x7d, 0x81, 0x18, 0x18, 0x0d, 0x81,
	0x18, 0x08, 0xc4, 0xb1, 0x21, 0x09, 0xc4, 0xb1, 0x40, 0xd8, 0x86, 0x2c, 0x10, 0xb6, 0x40, 0x9c,
	0x18, 0x8a, 0x40, 0x9c, 0x08, 0xc4, 0xd0, 0x50, 0x05, 0x62, 0x68, 0x7e, 0xad, 0x82, 0x5a, 0x64,
	0xd3, 0xb3, 0xff, 0x97, 0x70, 0xcc, 0xf9, 0x73, 0x4d, 0x7d, 0xeb, 0x5f, 0xd4, 0x64, 0x7e, 0x7a,
	0xbe, 0xcf, 0x1e, 0xfc, 0xfd, 0x3e, 0xb3, 0x05, 0xc0, 0x69, 0x9a, 0x3e, 0x6e, 0xbe, 0x98, 0xdf,
	0xab, 0xa0, 0x8c, 0xd8, 0x6a, 0xcc, 0x36, 0x8c, 0x10, 0x68, 0x2c, 0xd8, 0x86, 0xf1, 0x33, 0x0d,
	0xe4, 0xdf, 0xe4, 0x1d, 0xd4, 0xb6, 0x43, 0xfe, 0xa6, 0x66, 0xa9, 0xdd, 0x72, 0xcd, 0x26, 0x15,
	0xac, 0x6d, 0x87, 0xe4, 0x3d, 0xd4, 0xb7, 0x3d, 0x9b, 0x47, 0xa0, 0x59, 0xcd, 0xee, 0x73, 0xce,
	0x93, 0x0a, 0xe6, 0x3a, 0xb7, 0xfb, 0x16, 0xef, 0xff, 0xc5, 0xee, 0x5b, 0xdc, 0xee, 0x5b, 0xdc,
	0xb6, 0x07, 0x7c, 0x33, 0x5e, 0x6c, 0x7b, 0xc0, 0x6d, 0x7b, 0x40, 0x0e, 0x40, 0x8a, 0xf3, 0x0a,
	0xf9, 0x62, 0x68, 0x96, 0xd6, 0x7d, 0x29, 0x7a, 0x52, 0xc1, 0xc2, 0x3b, 0x55, 0x40, 0xba, 0xcd,
	0x65, 0xf3, 0x47, 0x1d, 0xe4, 0x11, 0x5b, 0xcd, 0xb2, 0x25, 0xd9, 0x03, 0x79, 0xcd, 0x9e, 0xc2,
	0x64, 0xc1, 0xfb, 0x68, 0xa3, 0xb4, 0x66, 0x4f, 0xd3, 0x05, 0x39, 0x04, 0x39, 0x7b, 0xd8, 0xae,
	0xa3, 0x98, 0x37, 0xd3, 0xb1, 0x3a, 0xdd, 0x82, 0xef, 0xfa, 0x5c, 0xc5, 0xd2, 0xcd, 0x8f, 0x27,
	0x59, 0xc8, 0xa2, 0x3b, 0xde, 0x97, 0x8a, 0x52, 0x92, 0x39, 0xd1, 0x1d, 0xe9, 0x40, 0x2d, 0x59,
	0xf0, 0x5e, 0xda, 0x58, 0x4b, 0x16, 0xe4, 0x00, 0xd4, 0x88, 0xad, 0x42, 0x9e, 0x97, 0x54, 0xa6,
	0x53, 0xe6, 0x88, 0x4a, 0x54, 0x06, 0xfa, 0x16, 0xd4, 0x34, 0x5b, 0xf2, 0x51, 0x94, 0xfb, 0xad,
	0xa4, 0xd9, 0x32, 0x1f, 0x03, 0xf9, 0x08, 0xbb, 0xb9, 0xb5, 0x8e, 0xd9, 0x82, 0xdd, 0xdc, 0xc7,
	0x05, 0x53, 0x6c, 0xf8, 0x4e, 0x9a, 0x2d, 0xb1, 0xd4, 0x39, 0xfb, 0x01, 0xb4, 0x24, 0x0b, 0xa3,
	0x75, 0xb2, 0x49, 0x22, 0x76, 0xcf, 0xb7, 0x5c, 0x45, 0x48, 0xb2, 0x51, 0xa9, 0x98, 0x3f, 0xab,
	0x20, 0x17, 0x6d, 0x90, 0x16, 0xa8, 0x48, 0x7d, 0x8a, 0x57, 0x74, 0xac, 0x57, 0x08, 0x80, 0x7c,
	0xe1, 0x5e, 0x06, 0x97, 0xbe, 0x5e, 0x25, 0x3a, 0xb4, 0x8a, 0xef, 0xd0, 0x77, 0x9d, 0x2b, 0xaa,
	0xd7, 0x48, 0x13, 0xa4, 0xd1, 0xc4, 0xf1, 0x7c, 0xbd, 0x4e, 0xda, 0xd0, 0x0c, 0xa8, 0x4b, 0x67,
	0x34, 0xc0, 0x6b, 0xbd, 0x91, 0xb3, 0xee, 0xf4, 0x7c, 0x12, 0xf8, 0xe1, 0x19, 0x7a, 0xf3, 0x40,
	0x97, 0xc8, 0x0e, 0x68, 0xa5, 0x82, 0xd4, 0x41, 0x5d, 0x26, 0xaf, 0x41, 0x9f, 0x79, 0x81, 0x87,
	0xe1, 0xc8, 0x9b, 0x07, 0xe8, 0xb9, 0x2e, 0x45, 0x5d, 0x21, 0xaf, 0x60, 0x67, 0x8c, 0xd3, 0x2b,
	0xfa, 0x5b, 0xf6, 0x75, 0x95, 0x10, 0xe8, 0x94, 0xe2, 0x78, 0xea, 0x5f, 0xb8, 0xce, 0xb5, 0xde,
	0x24, 0x6f, 0x80, 0xf8, 0x9e, 0xeb, 0x60, 0x38, 0x73, 0xfc, 0x80, 0x62, 0xf9, 0x0e, 0x90, 0x3d,
	0xd8, 0xfd, 0x43, 0xe7, 0xaf, 0x69, 0x79, 0x41, 0x3e, 0x9d, 0xfb, 0x1e, 0x86, 0xa7, 0x9e, 0x83,
	0x63, 0xbd, 0x45, 0x34, 0x50, 0x46, 0x13, 0x07, 0xcf, 0x29, 0xea, 0x6d, 0xf3, 0x10, 0x9a, 0x23,
	0xb6, 0xf2, 0xa3, 0xcf, 0x71, 0x9a, 0xa7, 0x5e, 0x4f, 0xb3, 0xa5, 0x51, 0xdd, 0xaf, 0x1f, 0x69,
	0x96, 0x52, 0x8e, 0x19, 0x73, 0xed, 0x46, 0xe6, 0x7f, 0xcc, 0xfe, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x49, 0xdc, 0x08, 0xc7, 0x3e, 0x05, 0x00, 0x00,
}
